SELECT * FROM customer_trends;

-- Q1) What is the total revenue generated by each gender?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer_trends
GROUP BY gender;


-- Q2) Which customers used a discount, but still spent more than the avg amount?
SELECT customer_id, purchase_amount
FROM customer_trends
WHERE 
	discount_applied = 'Yes' and 
    purchase_amount >= (select AVG(purchase_amount) FROM customer_trends);


-- Q3) Top 5 products with the highest avg review rating
SELECT item_purchased, ROUND(AVG(review_rating),2) AS "Average Product Rating"
FROM customer_trends
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
LIMIT 5;


-- Q4) Compare avg purchase amounts between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_purch
FROM customer_trends
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type;

# comparing avg purchase amounts between all types of shipping
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_purch
FROM customer_trends
WHERE shipping_type in ('Standard', 'Express', 'Free Shipping', '2-Day Shipping', 'Store Pickup', 'Next Day Air')
GROUP BY shipping_type;


-- Q4) Compare avg spend and total revenue between subs and non-subs to see if subs spend more
SELECT subscription_status, COUNT(customer_id) as total_customers, 
	ROUND(AVG(purchase_amount), 2) as avg_spend, 
	ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer_trends
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;


-- Q5) Which 5 products have the highest percentage of purchases with discounts applied?
# number of times each the top 5 items were sold when they were discounted
SELECT item_purchased, COUNT(*) AS times_sold
FROM customer_trends
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY times_sold DESC
LIMIT 5;

# the percentage of all purchases that had a discount
SELECT ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) AS discounted_percentage
FROM customer_trends;

# the percentage of discounted sales per all items
SELECT item_purchased, 
	ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) AS discounted_percentage
FROM customer_trends
GROUP BY item_purchased
ORDER BY discounted_percentage DESC;

# for the TOP 5 MOST SOLD items, what % of their sales were discounted
SELECT item_purchased, COUNT(*) AS total_sales,
    SUM(discount_applied = 'Yes') AS discounted_sales,
    ROUND(100.0 * SUM(discount_applied = 'Yes') / COUNT(*), 2) AS discounted_percentage
FROM customer_trends
GROUP BY item_purchased
ORDER BY total_sales DESC
LIMIT 5;

# the 5 items that have the HIGHEST percentage of discounted sales
SELECT item_purchased, 
	ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer_trends
GROUP BY item_purchased
ORDER BY discount_rate desc
LIMIT 5;



-- Q6) Segment customers into new, returning, and loyal, based on their total number of previous purchases
SELECT customer_id, previous_purchases,
    CASE
        WHEN previous_purchases <= 2 THEN 'New'
        WHEN previous_purchases BETWEEN 3 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM customer_trends;


SELECT
    CASE
        WHEN previous_purchases <= 2 THEN 'New'
        WHEN previous_purchases BETWEEN 3 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_type,
    COUNT(*) AS customer_count
FROM customer_trends
GROUP BY customer_type;

-- Q7) Find the top 3 most purchased products within each category
WITH item_counts AS (SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_trends
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q8) Find out if repeat customers (more than 5 purchases) are likely to subscribe.
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_trends
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q9) Find the revenuew contribution of each age group.
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer_trends
GROUP BY age_group
ORDER BY total_revenue DESC;